title: Samuel Silva
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/samuelsilvadev.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Samuel Silva
tagline: Frontend Developer
about-description: Hello! I'm a Frontend Developer with 5 years of experience. Currently living in Porto, Portugal. Since the beginning of my journey I've been collaborating with very talented people which help me a lot through my career. I'm interested in everything about the web, I also like to deep dive in concepts to really understanding what I am doing and how to delivery the best possible result.
pic: profile.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below


# Contact links
email: samuelsilvawb@gmail.com
phone: +351 911975267
website: samuelsilvadev.github.io 
linkedin: samuel-silva-olv
github: samuelsilvadev 
twitter: '@samuelsilvadev'

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
